DROP TABLE IF EXISTS
    users,
    locations,
    categories,
    events,
    requests,
    compilations,
    events_compilations,
    comments;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         VARCHAR(1000) NOT NULL,
    category_id        BIGINT        NOT NULL,
    confirmed_requests BIGINT        NOT NULL,
    created_on         TIMESTAMP     NOT NULL,
    description        VARCHAR(1000) NOT NULL,
    event_date         TIMESTAMP     NOT NULL,
    initiator_id       BIGINT        NOT NULL REFERENCES users (id),
    location_id        BIGINT        NOT NULL REFERENCES locations (id),
    paid               BOOLEAN       NOT NULL DEFAULT false,
    participant_limit  BIGINT        NOT NULL,
    published_on       TIMESTAMP,
    request_moderation BOOLEAN       NOT NULL DEFAULT true,
    state              VARCHAR(30)   NOT NULL,
    title              VARCHAR(400)  NOT NULL,
    views              BIGINT        NOT NULL
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_on   TIMESTAMP NOT NULL,
    requestor_id BIGINT    NOT NULL REFERENCES users (id),
    event_id     BIGINT    NOT NULL REFERENCES events (id),
    state        VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN      NOT NULL DEFAULT false,
    title  VARCHAR(400) NOT NULL
);

CREATE TABLE IF NOT EXISTS events_compilations
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       BIGINT NOT NULL REFERENCES events (id),
    compilation_id BIGINT NOT NULL REFERENCES compilations (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text       VARCHAR(400) NOT NULL,
    event_id   BIGINT       NOT NULL REFERENCES events (id),
    author_id  BIGINT       NOT NULL REFERENCES users (id),
    created_on TIMESTAMP    NOT NULL
)
